# Generated by Django 4.1.7 on 2023-03-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_description_job_experience_year_job_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=1),
        ),
    ]
