# Generated by Django 4.1.7 on 2023-03-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
    ]
